### PR TITLE
Fix duration column time formatting #20

### LINKED ISSUE #20: Duration column time formatting is incorrect
For milliseconds - **1856932**

The output should be - `30 min, 56 sec`

But the actual output is - `01 hrs, 30 min, 56 sec`

### PR DESCRIPTION
**Pull request by soulchainer**
Closes #20

### CODE REVIEW

File: lib/util.js [hunk 1]
```diff
@@ -57,9 +57,9 @@ exports.formatTimestampToDate = function(timestamp) {
 };
 
 exports.formatMs = function(ms) {
-  const seconds = Math.floor((ms / 1000) % 60);
-  const minutes = Math.floor((ms / (1000 * 60)) % 60);
-  const hours = Math.floor((ms / (1000 * 60 * 24)) % 60);
+  const seconds = Math.floor(ms / 1000) % 60;
+  const minutes = Math.floor(ms / (1000 * 60)) % 60;
+  const hours = Math.floor(ms / (1000 * 60 * 60));
   let formattedTime = '';
```
Comment (m-sureshraj) [inline lib/util.js:64]: Could you replace constructing `formattedTime` logic with the following changes?

```js
if (hours) {
  formattedTime += hours.toString(10).padStart(2, '0') + ' hrs';

  (minutes || seconds) && (formattedTime += ', ');
}

if (minutes) {
  formattedTime += minutes.toString(10).padStart(2, '0') + ' min';

  seconds && (formattedTime += ', ');
}

if (seconds) formattedTime += seconds.toString(10).padStart(2, '0') + ' sec';
```

**Comment by m-sureshraj** [comment]
Thank you for the contribution @soulchainer.

File: lib/util.js (hunk 1 above)
Comment (soulchainer) [reply lib/util.js:64]: Hi, @m-sureshraj! :D.

Of course I can! :D. But now, checking it, I think it would like better to change the structure and use an array.
I mean this (give me your opinion):

```
const formattedTime = [];

if (hours) formattedTime.push(hours.toString(10).padStart(2, '0')) + ' hrs';
if (minutes) formattedTime.push(minutes.toString(10).padStart(2, '0')) + ' min';
if (seconds) formattedTime.push(seconds.toString(10).padStart(2, '0')) + ' sec';

return formattedTime.join(', ');
```

It would get the same result you want (I didn't get previously that there would be a problem when, as example, there weren't any seconds left, in the formatting), and it's more compact and readable. And you dont need to use that extra short-circuit conditions this way. Do you like it?

If not and if you want it the way you explicitly asked for, I have no problem adding that instead. What do you say then?

Comment (m-sureshraj) [reply lib/util.js:64]: Neat! I like your solution :+1:.

Comment (soulchainer) [reply lib/util.js:64]: Change pushed :+1: .

**Comment by m-sureshraj** [comment]
Nice. The changes are looks good to me. Please squash the commits into one and update the PR, then I can merge this into master. 

Use the following commit message format:

fix: commit message

**Comment by soulchainer** [comment]
Done ;).

But, for the future, maybe you should set squash in the repo options and you could have done that quicker, right? → https://help.github.com/en/github/administering-a-repository/configuring-commit-squashing-for-pull-requests

**Comment by m-sureshraj** [comment]
Hummn, I didn't know that until now. Thanks for the link.

**Review by m-sureshraj — APPROVED** [review]
